# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 06:10
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160414_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=redactor.fields.RedactorField(verbose_name='Text'),
        ),
    ]
