# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 05:41
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160416_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
